import { CommentListType, CommentReplyListType } from "@shared/ui";
import { colors } from "@theme/token";

import { RecordBookPostType, RecordBookResponse } from "../types";

// TODO: 추후 type은 서버에서 사용하는 것으로 수정 필요
export const GROUP_RECORD_SORT = [
  {
    label: "최신순",
    type: "latest",
  },
  {
    label: "인기순",
    type: "like",
  },
  {
    label: "댓글 많은순",
    type: "comment",
  },
];

export const DUMMY_RECORD_BOOK_POST_LIST: RecordBookPostType[] = [
  {
    postId: 1,
    postDate: "3시간 전",
    postType: "TEXT",
    page: 12,
    userId: 101,
    nickName: "책읽는사람",
    profileImageUrl: "https://picsum.photos/seed/user101/100/100",
    content:
      "첫 장부터 분위기가 무겁게 깔려서 몰입이 잘 됐다. 주인공의 감정선이 생각보다 섬세하게 느껴졌다.",
    likeCount: 12,
    commentCount: 3,
    isOverview: false,
    isLiked: true,
    isWriter: true,
    isLocked: false,
    voteItems: [],
  },
  {
    postId: 2,
    postDate: "12시간 전",
    postType: "TEXT",
    page: 28,
    userId: 102,
    nickName: "문장수집가",
    profileImageUrl: "https://picsum.photos/seed/user102/100/100",
    content:
      "이 부분에서 인물 간의 관계가 조금씩 드러나는 게 좋았다. 아직은 누가 진짜 중요한 인물인지 헷갈린다.",
    likeCount: 7,
    commentCount: 1,
    isOverview: false,
    isLiked: false,
    isWriter: false,
    isLocked: false,
    voteItems: [],
  },
  {
    postId: 3,
    postDate: "2026-05-13",
    postType: "VOTE",
    page: 35,
    userId: 103,
    nickName: "독서모임장",
    profileImageUrl: "https://picsum.photos/seed/user103/100/100",
    content: "현재까지 가장 인상 깊었던 인물은 누구인가요?",
    likeCount: 18,
    commentCount: 6,
    isOverview: false,
    isLiked: false,
    isWriter: false,
    isLocked: false,
    voteItems: [
      {
        voteItemId: 1,
        itemName: "주인공",
        count: 8,
        isVoted: true,
      },
      {
        voteItemId: 2,
        itemName: "주인공의 친구",
        count: 5,
        isVoted: false,
      },
      {
        voteItemId: 3,
        itemName: "새롭게 등장한 인물",
        count: 3,
        isVoted: false,
      },
    ],
  },
  {
    postId: 4,
    postDate: "2026-05-13",
    postType: "TEXT",
    page: 48,
    userId: 104,
    nickName: "조용한독자",
    profileImageUrl: "https://picsum.photos/seed/user104/100/100",
    content:
      "이 장면은 나중에 다시 언급될 것 같다. 단순한 설명처럼 보이지만 복선처럼 느껴졌다.",
    likeCount: 4,
    commentCount: 0,
    isOverview: false,
    isLiked: false,
    isWriter: false,
    isLocked: false,
    voteItems: [],
  },
  {
    postId: 5,
    postDate: "2026-05-12",
    postType: "TEXT",
    page: 60,
    userId: 105,
    nickName: "요약왕",
    profileImageUrl: "https://picsum.photos/seed/user105/100/100",
    content:
      "1장에서는 인물의 배경과 현재 상황이 주로 설명된다. 사건 자체보다는 인물의 내면 묘사가 중심이다.",
    likeCount: 22,
    commentCount: 5,
    isOverview: true,
    isLiked: true,
    isWriter: false,
    isLocked: false,
    voteItems: [],
  },
  {
    postId: 6,
    postDate: "2026-05-12",
    postType: "TEXT",
    page: 72,
    userId: 106,
    nickName: "스포방지",
    profileImageUrl: "https://picsum.photos/seed/user106/100/100",
    content: "잠긴 기록입니다. 해당 페이지에 도달한 뒤 확인할 수 있습니다.",
    likeCount: 0,
    commentCount: 0,
    isOverview: false,
    isLiked: false,
    isWriter: false,
    isLocked: true,
    voteItems: [],
  },
  {
    postId: 7,
    postDate: "2026-05-11",
    postType: "VOTE",
    page: 85,
    userId: 101,
    nickName: "책읽는사람",
    profileImageUrl: "https://picsum.photos/seed/user101/100/100",
    content: "이번 챕터의 분위기는 어떻게",
    likeCount: 9,
    commentCount: 2,
    isOverview: false,
    isLiked: false,
    isWriter: true,
    isLocked: false,
    voteItems: [
      {
        voteItemId: 4,
        itemName: "차분하다",
        count: 6,
        isVoted: false,
      },
      {
        voteItemId: 5,
        itemName: "긴장감 있다",
        count: 11,
        isVoted: true,
      },
      {
        voteItemId: 6,
        itemName: "조금 어렵다",
        count: 2,
        isVoted: false,
      },
    ],
  },
];

export const DUMMY_RECORD_BOOK_RESPONSE: RecordBookResponse = {
  postList: DUMMY_RECORD_BOOK_POST_LIST,
  roomId: 3,
  isbn: "9788936433598",
  isOverviewEnabled: false,
  nextCursor: "", // 이건 추후 무한스크롤에 사용. 현재는 신경 X
  isLast: false, // 이건 추후 무한스크롤에 사용. 현재는 신경 X
};

export const DUMMY_RECORD_COMMENT_REPLY_LIST: CommentReplyListType[] = [
  {
    commentId: 8,
    parentCommentCreatorNickname: "user1",
    creatorId: 12,
    creatorProfileImageUrl: "https://placehold.co/30/png",
    creatorNickname: "user12",
    aliasName: "칭호칭호",
    aliasColor: colors.character.mint,
    postDate: "12시간 전",
    content: "답글입니다.",
    likeCount: 5,
    isLike: false,
    isWriter: true,
  },
  {
    commentId: 456,
    parentCommentCreatorNickname: "user12",
    creatorId: 123,
    creatorProfileImageUrl: "https://placehold.co/30/png",
    creatorNickname: "user123",
    aliasName: "칭호칭호",
    aliasColor: colors.character.lavender,
    postDate: "8시간 전",
    content:
      "답글입니다. ~~~~~ 긴 댓글? 댓글 내용을 입력하세요. 긴 댓글? 댓글 내용을 입력하세요. 긴 댓글? 댓글 내용을 입력하세요. 긴 댓글? 댓글 내용을 입력하세요. 긴 댓글? 댓글 내용을 입력하세요. 긴 댓글? 댓글 내용을 입력하세요. 긴 댓글? 댓글 내용을 입력하세요.",
    likeCount: 9,
    isLike: false,
    isWriter: false,
  },
];

export const DUMMY_RECORD_COMMENT_LIST: CommentListType[] = [
  {
    commentId: 3,
    creatorId: 5,
    creatorProfileImageUrl: "https://placehold.co/30/png",
    creatorNickname: "user1",
    aliasName: "칭호",
    aliasColor: colors.character.pink,
    postDate: "2026.02.12",
    content: `입력하세요. 댓글 내용을 입력하세요오.\n줄바꿈 할게요.\n댓글 내용을 입력하세요. 댓글 내용을 입력하세요. `,
    likeCount: 12,
    isLike: true,
    isDeleted: false,
    isWriter: false,
    replyList: DUMMY_RECORD_COMMENT_REPLY_LIST,
  },
  {
    commentId: 123,
    creatorId: 16,
    creatorProfileImageUrl: "https://placehold.co/30/png",
    creatorNickname: "테스트유저16",
    aliasName: "칭호2",
    aliasColor: colors.character.orange,
    postDate: "5시간 전",
    content: `입력하세요. 댓글 내용을 입력하세요오.\n줄바꿈 할게요.\n댓글 내용을 입력하세요. 댓글 내용을 입력하세요. `,
    likeCount: 135,
    isLike: true,
    isDeleted: false,
    isWriter: false,
    replyList: [],
  },
];
