import { DailyGreetingCommentType } from "../types";

export const DUMMY_DAILY_GREETING: DailyGreetingCommentType[] = [
  {
    attendanceCheckId: 1,
    creatorId: 101,
    creatorNickname: "문장수집가",
    creatorProfileImageUrl: "https://placehold.co/24x24/png",
    todayComment: "오늘 읽은 한 문장이 오래 남았어요.",
    postDate: "5분 전",
    date: "2025-08-17",
    isWriter: true,
  },
  {
    attendanceCheckId: 2,
    creatorId: 102,
    creatorNickname: "새벽독서",
    creatorProfileImageUrl: "https://placehold.co/24x24/png",
    todayComment: "출근길에 읽으니 책장이 더 잘 넘어가네요.",
    postDate: "18분 전",
    date: "2025-08-17",
    isWriter: false,
  },
  {
    attendanceCheckId: 3,
    creatorId: 103,
    creatorNickname: "책갈피",
    creatorProfileImageUrl: "https://placehold.co/24x24/png",
    todayComment: "주인공의 선택이 계속 생각나요.",
    postDate: "1시간 전",
    date: "2025-08-17",
    isWriter: false,
  },
  {
    attendanceCheckId: 4,
    creatorId: 104,
    creatorNickname: "느린문장",
    creatorProfileImageUrl: "https://placehold.co/24x24/png",
    todayComment: "오늘은 짧게 읽었지만 꾸준히 이어갑니다.",
    postDate: "2시간 전",
    date: "2025-08-17",
    isWriter: false,
  },
  {
    attendanceCheckId: 5,
    creatorId: 105,
    creatorNickname: "밤의서재",
    creatorProfileImageUrl: "https://placehold.co/24x24/png",
    todayComment: "마지막 장을 덮고 나니 조용히 여운이 남네요.",
    postDate: "어제",
    date: "2025-08-16",
    isWriter: false,
  },
  {
    attendanceCheckId: 6,
    creatorId: 106,
    creatorNickname: "책읽는하루",
    creatorProfileImageUrl: "https://placehold.co/24x24/png",
    todayComment: "오늘 분량은 다 못 읽었지만 좋은 문장을 발견했어요.",
    postDate: "어제",
    date: "2025-08-16",
    isWriter: false,
  },
  {
    attendanceCheckId: 7,
    creatorId: 107,
    creatorNickname: "여백",
    creatorProfileImageUrl: "https://placehold.co/24x24/png",
    todayComment: "같은 문장을 두 번 읽게 되는 날이네요.",
    postDate: "2일 전",
    date: "2025-08-15",
    isWriter: false,
  },
  {
    attendanceCheckId: 8,
    creatorId: 108,
    creatorNickname: "한페이지",
    creatorProfileImageUrl: "https://placehold.co/24x24/png",
    todayComment: "짧게라도 매일 읽으니 이야기의 흐름이 이어져요.",
    postDate: "2일 전",
    date: "2025-08-15",
    isWriter: false,
  },
  {
    attendanceCheckId: 9,
    creatorId: 109,
    creatorNickname: "초록책상",
    creatorProfileImageUrl: "https://placehold.co/24x24/png",
    todayComment: "오늘은 등장인물의 마음이 조금 이해됐어요.",
    postDate: "3일 전",
    date: "2025-08-15",
    isWriter: false,
  },
  {
    attendanceCheckId: 10,
    creatorId: 110,
    creatorNickname: "문학산책",
    creatorProfileImageUrl: "https://placehold.co/24x24/png",
    todayComment: "책 속 배경을 상상하면서 읽으니 더 몰입됐습니다.",
    postDate: "3일 전",
    date: "2025-08-15",
    isWriter: false,
  },
  {
    attendanceCheckId: 11,
    creatorId: 111,
    creatorNickname: "읽는습관",
    creatorProfileImageUrl: "https://placehold.co/24x24/png",
    todayComment: "잠들기 전에 읽는 시간이 제일 차분해요.",
    postDate: "4일 전",
    date: "2025-08-15",
    isWriter: false,
  },
  {
    attendanceCheckId: 12,
    creatorId: 112,
    creatorNickname: "파란책갈피",
    creatorProfileImageUrl: "https://placehold.co/24x24/png",
    todayComment: "오늘 읽은 부분은 대화가 많아서 금방 읽혔어요.",
    postDate: "4일 전",
    date: "2025-08-13",
    isWriter: false,
  },
  {
    attendanceCheckId: 13,
    creatorId: 113,
    creatorNickname: "느긋한독자",
    creatorProfileImageUrl: "https://placehold.co/24x24/png",
    todayComment: "급하게 넘기지 않고 천천히 읽어보는 중입니다.",
    postDate: "5일 전",
    date: "2025-08-12",
    isWriter: false,
  },
  {
    attendanceCheckId: 14,
    creatorId: 114,
    creatorNickname: "기록하는밤",
    creatorProfileImageUrl: "https://placehold.co/24x24/png",
    todayComment: "인상 깊은 문장을 따로 적어두고 싶어졌어요.",
    postDate: "5일 전",
    date: "2025-08-12",
    isWriter: false,
  },
  {
    attendanceCheckId: 15,
    creatorId: 115,
    creatorNickname: "서랍속책",
    creatorProfileImageUrl: "https://placehold.co/24x24/png",
    todayComment: "생각보다 무거운 장면이라 잠시 쉬어가려 합니다.",
    postDate: "6일 전",
    date: "2025-08-12",
    isWriter: false,
  },
  {
    attendanceCheckId: 16,
    creatorId: 116,
    creatorNickname: "오후의책",
    creatorProfileImageUrl: "https://placehold.co/24x24/png",
    todayComment: "카페에서 읽으니 집중이 잘 됐어요.",
    postDate: "6일 전",
    date: "2025-08-12",
    isWriter: false,
  },
  {
    attendanceCheckId: 17,
    creatorId: 117,
    creatorNickname: "문장노트",
    creatorProfileImageUrl: "https://placehold.co/24x24/png",
    todayComment: "이야기가 본격적으로 움직이기 시작했네요.",
    postDate: "7일 전",
    date: "2025-08-10",
    isWriter: false,
  },
  {
    attendanceCheckId: 18,
    creatorId: 118,
    creatorNickname: "단정한책장",
    creatorProfileImageUrl: "https://placehold.co/24x24/png",
    todayComment: "오늘도 체크인 완료. 내일은 조금 더 읽어볼게요.",
    postDate: "7일 전",
    date: "2025-08-10",
    isWriter: false,
  },
  {
    attendanceCheckId: 19,
    creatorId: 119,
    creatorNickname: "조용한독서",
    creatorProfileImageUrl: "https://placehold.co/24x24/png",
    todayComment: "첫 장보다 지금이 훨씬 재밌어졌어요.",
    postDate: "8일 전",
    date: "2025-08-09",
    isWriter: false,
  },
  {
    attendanceCheckId: 20,
    creatorId: 120,
    creatorNickname: "책과커피",
    creatorProfileImageUrl: "https://placehold.co/24x24/png",
    todayComment: "한 문단이 길게 남는 하루였습니다.",
    postDate: "8일 전",
    date: "2025-08-09",
    isWriter: false,
  },
];
