import { colors } from "@theme/token";

export const DUMMY_BOOK_DETAIL = {
  title: "채식주의자",
  imageUrl: "https://placehold.co/400/png?text=book-image",
  authorName: "한강",
  publisher: "창비",
  isbn: "9788936434120",
  description:
    "인터내셔널 부커상, 산클레멘테 문학상 수상작전세계가 주목한 한강의 역작을 다시 만나다. 2016년 인터내셔널 부커상을 수상하며 한국문학의 입지를 한단계 확장시킨 한강의 장편소설 『채식주의자』를 15년 만에 새로운 장정으로 선보인다.\n\n 상처받은 영혼의 고통과 식물적 상상력의 강렬한 결합을 정교한 구성과 흡인력 있는 문체로 보여주는 이 작품은 섬뜩한 아름다움의 미학을 한강만의 방식으로 완성한 역작이다. “탄탄하고 정교하며 충격적인 작품으로, 독자들의 마음에 그리고 아마도 그들의 꿈에 오래도록 머물 것이다”라는 평을 받으며 인터내셔널 부커상을 수상했던 『채식주의자』는 “미국 문학계에 파문을 일으키면서도 독자들과 공명할 것으로 보인다”(뉴욕타임스), “놀라울 정도로 아름다운 산문과 믿을 수 없을 만큼 폭력적인 내용의 조합이 충격적이다”(가디언)라는 해외서평을 받았고 2018년에는 스페인에서 산클레멘테 문학상을 받는 등 전세계에서 뜨거운 반응을 일으켰다. 국내에서는 현재까지 100만부 가까이 판매되었다.『채식주의자』는 어느 날부터 육식을 거부하며 가족들과 갈등을 빚기 시작하는 ‘영혜’가 중심인물로 등장하는 장편소설이다. 하지만 소설은 영혜를 둘러싼 세 인물인 남편, 형부, 언니의 시선에서 서술되며 영혜는 단 한번도 주도적인 화자의 위치를 얻지 못한다. 가족의 이름으로 자행되는 가부장의 폭력, 그리고 그 폭력에 저항하며 금식을 통해 동물성을 벗어던지고 나무가 되고자 한 영혜가 보여주는 식물적 상상력의 경지는 모든 세대 독자를 아우르며 더 크나큰 공명을 이루어낼 것이다.",
  recruitingRoomCount: 4,
  readCount: 321,
  isSaved: true,
};

export const DUMMY_BOOK_FEED_PREVIEW_LIST = [
  {
    feedId: 1,
    creatorId: 1,
    creatorNickname: "user.01",
    creatorProfileImageUrl: "https://placehold.co/36/png",
    aliasName: "문학 칭호",
    aliasColor: colors.character.lavender,
    postDate: "30분 전",
    isbn: "1234a",
    bookTitle: "소년이 온다",
    bookAuthor: "한강",
    contentBody: "책이름을 입력해주세요책... 한강한강한강한강...",
    contentUrls: [
      "https://placehold.co/100/png",
      "https://placehold.co/100/png",
      "https://placehold.co/100/png",
    ],
    likeCount: 132,
    commentCount: 4,
    isSaved: false,
    isLiked: true,
    isWriter: true,
  },
  {
    feedId: 2,
    creatorId: 2,
    creatorNickname: "thip.dev",
    creatorProfileImageUrl: "https://placehold.co/36/png?text=T",
    aliasName: "사회학자",
    aliasColor: colors.character.orange,
    postDate: "2시간 전",
    isbn: "9788936434120",
    bookTitle: "채식주의자",
    bookAuthor: "한강",
    contentBody:
      "짧게 적는 감상. 문장이 너무 날카롭고 아름다워서 몇 번이고 다시 읽게 된다. 짧게 적는 감상. 문장이 너무 날카롭고 아름다워서 몇 번이고 다시 읽게 된다. 짧게 적는 감상. 문장이 너무 날카롭고 아름다워서 몇 번이고 다시 읽게 된다. 짧게 적는 감상. 문장이 너무 날카롭고 아름다워서 몇 번이고 다시 읽게 된다. 짧게 적는 감상. 문장이 너무 날카롭고 아름다워서 몇 번이고 다시 읽게 된다. 짧게 적는 감상. 문장이 너무 날카롭고 아름다워서 몇 번이고 다시 읽게 된다.",
    contentUrls: ["https://placehold.co/100/png"],
    likeCount: 54,
    commentCount: 12,
    isSaved: true,
    isLiked: false,
    isWriter: false,
  },
  {
    feedId: 3,
    creatorId: 3,
    creatorNickname: "moon.reader",
    creatorProfileImageUrl: "https://placehold.co/36/png?text=M",
    aliasName: "과학자",
    aliasColor: colors.character.mint,
    postDate: "어제",
    isbn: "9788956609959",
    bookTitle: "이기적 유전자. 대충 되게 긴 제목입니다.",
    bookAuthor: "리처드 도킨스, 리처드 도킨스, 리처드 도킨스",
    contentBody:
      "밑줄 친 문장 정리 중. '생존'이라는 단어를 다시 생각하게 만드는 챕터였다. 밑줄 친 문장 정리 중. '생존'이라는 단어를 다시 생각하게 만드는 챕터였다. 밑줄 친 문장 정리 중. '생존'이라는 단어를 다시 생각하게 만드는 챕터였다. 밑줄 친 문장 정리 중. '생존'이라는 단어를 다시 생각하게 만드는 챕터였다. 밑줄 친 문장 정리 중. '생존'이라는 단어를 다시 생각하게 만드는 챕터였다. 밑줄 친 문장 정리 중. '생존'이라는 단어를 다시 생각하게 만드는 챕터였다. 밑줄 친 문장 정리 중. '생존'이라는 단어를 다시 생각하게 만드는 챕터였다. 밑줄 친 문장 정리 중. '생존'이라는 단어를 다시 생각하게 만드는 챕터였다.",
    contentUrls: [],
    likeCount: 201,
    commentCount: 33,
    isSaved: false,
    isLiked: true,
    isWriter: false,
  },
  {
    feedId: 4,
    creatorId: 4,
    creatorNickname: "han.gg",
    creatorProfileImageUrl: "https://placehold.co/36/png?text=H",
    aliasName: "예술가",
    aliasColor: colors.character.pink,
    postDate: "3일 전",
    isbn: "9788932917246",
    bookTitle: "아몬드",
    bookAuthor: "손원평",
    contentBody:
      "감정이 결핍된 소년이 세상을 배우는 방식이 너무 담담해서 오히려 더 크게 다가왔다.",
    contentUrls: [
      "https://placehold.co/100/png",
      "https://placehold.co/100/png",
      "https://placehold.co/100/png",
      "https://placehold.co/100/png",
      "https://placehold.co/100/png",
    ],
    likeCount: 89,
    commentCount: 7,
    isSaved: true,
    isLiked: true,
    isWriter: true,
  },
  {
    feedId: 5,
    creatorId: 5,
    creatorNickname: "paper.log",
    creatorProfileImageUrl: "https://placehold.co/36/png?text=P",
    aliasName: "철학자",
    aliasColor: colors.character.mint,
    postDate: "1주 전",
    isbn: "9788932473902",
    bookTitle: "데미안",
    bookAuthor: "헤르만 헤세",
    contentBody:
      "‘새는 알을 깨고 나온다’ 구절이 요즘 계속 맴돈다. 변화가 두려울 때마다 꺼내보는 문장.",
    contentUrls: ["https://placehold.co/100/png"],
    likeCount: 17,
    commentCount: 0,
    isSaved: false,
    isLiked: false,
    isWriter: false,
  },
  {
    feedId: 6,
    creatorId: 6,
    creatorNickname: "ku.room",
    creatorProfileImageUrl: "https://placehold.co/36/png?text=K",
    aliasName: "탐험가",
    aliasColor: colors.character.skyblue,
    postDate: "2주 전",
    isbn: "9788936433598",
    bookTitle: "작별하지 않는다",
    bookAuthor: "한강",
    contentBody:
      "긴 글 테스트용. \n\n줄바꿈도 있고, 문단도 여러 개. 이 정도 길이에서 더보기 처리/라인클램프가 잘 동작하는지 확인하려고 적어본다.",
    contentUrls: [
      "https://placehold.co/100/png",
      "https://placehold.co/100/png",
      "https://placehold.co/100/png",
    ],
    likeCount: 302,
    commentCount: 41,
    isSaved: true,
    isLiked: true,
    isWriter: false,
  },
  {
    feedId: 7,
    creatorId: 7,
    creatorNickname: "tiny.note",
    creatorProfileImageUrl: "https://placehold.co/36/png?text=N",
    aliasName: "독서가",
    aliasColor: colors.character.orange,
    postDate: "방금",
    isbn: "9788932921427",
    bookTitle: "불편한 편의점",
    bookAuthor: "김호연",
    contentBody: "가볍게 읽기 시작했는데 의외로 따뜻하다.",
    contentUrls: [],
    likeCount: 6,
    commentCount: 1,
    isSaved: false,
    isLiked: false,
    isWriter: true,
  },
  {
    feedId: 8,
    creatorId: 8,
    creatorNickname: "uiux.reader",
    creatorProfileImageUrl: "https://placehold.co/36/png?text=U",
    aliasName: "기획자",
    aliasColor: colors.character.lavender,
    postDate: "5일 전",
    isbn: "9788996991342",
    bookTitle: "도넛 경제학",
    bookAuthor: "케이트 레이워스",
    contentBody:
      "태그 UI/저장/좋아요 상태가 섞인 케이스 테스트. 카드 하단 액션이 길어져도 레이아웃이 안 깨지게.",
    contentUrls: [
      "https://placehold.co/100/png",
      "https://placehold.co/100/png",
    ],
    likeCount: 1200,
    commentCount: 128,
    isSaved: false,
    isLiked: true,
    isWriter: false,
  },
];
