import { type MyGroupCardProps } from "@shared/ui";

export const DUMMY_MY_GROUP_LIST: MyGroupCardProps[] = [
  {
    roomId: 1,
    bookImageUrl: "https://placehold.co/80x107/png",
    roomName: "데미안 천천히 읽는 모임",
    memberCount: 18,
    endDate: "30일 뒤",
    type: "playing",
  },
  {
    roomId: 2,
    bookImageUrl: "https://placehold.co/80x107/png",
    roomName: "불편한 편의점 같이 읽어요. 엄청 긴 제목은 어떻게 될까요?",
    recruitCount: 30,
    memberCount: 24,
    endDate: "5일 뒤",
    type: "recruiting",
  },
  {
    roomId: 3,
    bookImageUrl: "https://placehold.co/80x107/png",
    roomName: "아몬드 감상 나누는 북클럽",
    recruitCount: 20,
    memberCount: 14,
    endDate: "3일 뒤",
    type: "recruiting",
  },
  {
    roomId: 4,
    bookImageUrl: "https://placehold.co/80x107/png",
    roomName: "호르몬 체인지 완독 도전방",
    memberCount: 22,
    endDate: "15일 뒤",
    type: "playing",
  },
  {
    roomId: 5,
    bookImageUrl: "https://placehold.co/80x107/png",
    roomName: "채식주의자 깊게 읽는 모임",
    memberCount: 9,
    endDate: "7일 뒤",
    type: "playing",
  },
  {
    roomId: 6,
    bookImageUrl: "https://placehold.co/80x107/png",
    roomName: "소년이 온다 함께 읽기",
    memberCount: 27,
    endDate: "2일 뒤",
    type: "playing",
  },
  {
    roomId: 7,
    bookImageUrl: "https://placehold.co/80x107/png",
    roomName: "아몬드 감상 나누는 북클럽",
    recruitCount: 15,
    memberCount: 7,
    endDate: "3일 뒤",
    type: "recruiting",
  },
  {
    roomId: 8,
    bookImageUrl: "https://placehold.co/80x107/png",
    roomName: "호르몬 체인지 완독 도전방",
    memberCount: 22,
    endDate: "9일 뒤",
    type: "playing",
  },
  {
    roomId: 9,
    bookImageUrl: "https://placehold.co/80x107/png",
    roomName: "채식주의자 깊게 읽는 모임",
    memberCount: 9,
    endDate: "20일 뒤",
    type: "playing",
  },
  {
    roomId: 10,
    bookImageUrl: "https://placehold.co/80x107/png",
    roomName: "소년이 온다 함께 읽기",
    recruitCount: 10,
    memberCount: 6,
    endDate: "4일 뒤",
    type: "recruiting",
  },
];
