export const NOTIFICATION_ROUTE = {
  FEED_USER: "FEED_USER",
  FEED_DETAIL: "FEED_DETAIL",
  ROOM_MAIN: "ROOM_MAIN",
  ROOM_DETAIL: "ROOM_DETAIL",
  ROOM_POST_DETAIL: "ROOM_POST_DETAIL",
} as const;
