import { colors } from "@theme/token";

import { FeedPostPreviewType } from "../types";

export const DUMMY_FEED_PREVIEW_LIST: FeedPostPreviewType[] = [
  {
    feedId: 1,
    creatorId: 1,
    creatorNickname: "user.01",
    creatorProfileImageUrl: "https://placehold.co/36/png",
    aliasName: "문학 칭호",
    aliasColor: colors.character.lavender,
    postDate: "30분 전",
    isbn: "1234a",
    bookTitle: "소년이 온다",
    bookAuthor: "한강",
    contentBody: "책이름을 입력해주세요책... 한강한강한강한강...",
    contentUrls: [
      "https://placehold.co/100/png",
      "https://placehold.co/100/png",
      "https://placehold.co/100/png",
    ],
    likeCount: 132,
    commentCount: 4,
    isSaved: false,
    isLiked: true,
    isWriter: true,
  },
  {
    feedId: 2,
    creatorId: 2,
    creatorNickname: "thip.dev",
    creatorProfileImageUrl: "https://placehold.co/36/png?text=T",
    aliasName: "사회학자",
    aliasColor: colors.character.orange,
    postDate: "2시간 전",
    isbn: "9788936434120",
    bookTitle: "채식주의자",
    bookAuthor: "한강",
    contentBody:
      "짧게 적는 감상. 문장이 너무 날카롭고 아름다워서 몇 번이고 다시 읽게 된다. 짧게 적는 감상. 문장이 너무 날카롭고 아름다워서 몇 번이고 다시 읽게 된다. 짧게 적는 감상. 문장이 너무 날카롭고 아름다워서 몇 번이고 다시 읽게 된다. 짧게 적는 감상. 문장이 너무 날카롭고 아름다워서 몇 번이고 다시 읽게 된다. 짧게 적는 감상. 문장이 너무 날카롭고 아름다워서 몇 번이고 다시 읽게 된다. 짧게 적는 감상. 문장이 너무 날카롭고 아름다워서 몇 번이고 다시 읽게 된다.",
    contentUrls: ["https://placehold.co/100/png"],
    likeCount: 54,
    commentCount: 12,
    isSaved: true,
    isLiked: false,
    isWriter: false,
  },
  {
    feedId: 3,
    creatorId: 3,
    creatorNickname: "moon.reader",
    creatorProfileImageUrl: "https://placehold.co/36/png?text=M",
    aliasName: "과학자",
    aliasColor: colors.character.mint,
    postDate: "어제",
    isbn: "9788956609959",
    bookTitle: "이기적 유전자. 대충 되게 긴 제목입니다.",
    bookAuthor: "리처드 도킨스, 리처드 도킨스, 리처드 도킨스",
    contentBody:
      "밑줄 친 문장 정리 중. '생존'이라는 단어를 다시 생각하게 만드는 챕터였다. 밑줄 친 문장 정리 중. '생존'이라는 단어를 다시 생각하게 만드는 챕터였다. 밑줄 친 문장 정리 중. '생존'이라는 단어를 다시 생각하게 만드는 챕터였다. 밑줄 친 문장 정리 중. '생존'이라는 단어를 다시 생각하게 만드는 챕터였다. 밑줄 친 문장 정리 중. '생존'이라는 단어를 다시 생각하게 만드는 챕터였다. 밑줄 친 문장 정리 중. '생존'이라는 단어를 다시 생각하게 만드는 챕터였다. 밑줄 친 문장 정리 중. '생존'이라는 단어를 다시 생각하게 만드는 챕터였다. 밑줄 친 문장 정리 중. '생존'이라는 단어를 다시 생각하게 만드는 챕터였다.",
    contentUrls: [],
    likeCount: 201,
    commentCount: 33,
    isSaved: false,
    isLiked: true,
    isWriter: false,
  },
  {
    feedId: 4,
    creatorId: 4,
    creatorNickname: "han.gg",
    creatorProfileImageUrl: "https://placehold.co/36/png?text=H",
    aliasName: "예술가",
    aliasColor: colors.character.pink,
    postDate: "3일 전",
    isbn: "9788932917246",
    bookTitle: "아몬드",
    bookAuthor: "손원평",
    contentBody:
      "감정이 결핍된 소년이 세상을 배우는 방식이 너무 담담해서 오히려 더 크게 다가왔다.",
    contentUrls: [
      "https://placehold.co/100/png",
      "https://placehold.co/100/png",
      "https://placehold.co/100/png",
      "https://placehold.co/100/png",
      "https://placehold.co/100/png",
    ],
    likeCount: 89,
    commentCount: 7,
    isSaved: true,
    isLiked: true,
    isWriter: true,
  },
  {
    feedId: 5,
    creatorId: 5,
    creatorNickname: "paper.log",
    creatorProfileImageUrl: "https://placehold.co/36/png?text=P",
    aliasName: "철학자",
    aliasColor: colors.character.mint,
    postDate: "1주 전",
    isbn: "9788932473902",
    bookTitle: "데미안",
    bookAuthor: "헤르만 헤세",
    contentBody:
      "‘새는 알을 깨고 나온다’ 구절이 요즘 계속 맴돈다. 변화가 두려울 때마다 꺼내보는 문장.",
    contentUrls: ["https://placehold.co/100/png"],
    likeCount: 17,
    commentCount: 0,
    isSaved: false,
    isLiked: false,
    isWriter: false,
  },
  {
    feedId: 6,
    creatorId: 6,
    creatorNickname: "ku.room",
    creatorProfileImageUrl: "https://placehold.co/36/png?text=K",
    aliasName: "탐험가",
    aliasColor: colors.character.skyblue,
    postDate: "2주 전",
    isbn: "9788936433598",
    bookTitle: "작별하지 않는다",
    bookAuthor: "한강",
    contentBody:
      "긴 글 테스트용. \n\n줄바꿈도 있고, 문단도 여러 개. 이 정도 길이에서 더보기 처리/라인클램프가 잘 동작하는지 확인하려고 적어본다.",
    contentUrls: [
      "https://placehold.co/100/png",
      "https://placehold.co/100/png",
      "https://placehold.co/100/png",
    ],
    likeCount: 302,
    commentCount: 41,
    isSaved: true,
    isLiked: true,
    isWriter: false,
  },
  {
    feedId: 7,
    creatorId: 7,
    creatorNickname: "tiny.note",
    creatorProfileImageUrl: "https://placehold.co/36/png?text=N",
    aliasName: "독서가",
    aliasColor: colors.character.orange,
    postDate: "방금",
    isbn: "9788932921427",
    bookTitle: "불편한 편의점",
    bookAuthor: "김호연",
    contentBody: "가볍게 읽기 시작했는데 의외로 따뜻하다.",
    contentUrls: [],
    likeCount: 6,
    commentCount: 1,
    isSaved: false,
    isLiked: false,
    isWriter: true,
  },
  {
    feedId: 8,
    creatorId: 8,
    creatorNickname: "uiux.reader",
    creatorProfileImageUrl: "https://placehold.co/36/png?text=U",
    aliasName: "기획자",
    aliasColor: colors.character.lavender,
    postDate: "5일 전",
    isbn: "9788996991342",
    bookTitle: "도넛 경제학",
    bookAuthor: "케이트 레이워스",
    contentBody:
      "태그 UI/저장/좋아요 상태가 섞인 케이스 테스트. 카드 하단 액션이 길어져도 레이아웃이 안 깨지게.",
    contentUrls: [
      "https://placehold.co/100/png",
      "https://placehold.co/100/png",
    ],
    likeCount: 1200,
    commentCount: 128,
    isSaved: false,
    isLiked: true,
    isWriter: false,
  },
];
