import {
  CommentListType,
  CommentReplyListType,
  FeedPostDetailType,
} from "@shared/ui";
import { colors } from "@theme/token";

export const DUMMY_FEED_DETAIL: FeedPostDetailType = {
  feedId: 3,
  creatorId: 3,
  creatorNickname: "moon.reader",
  creatorProfileImageUrl: "https://placehold.co/36/png?text=M",
  aliasName: "과학자",
  aliasColor: colors.character.mint,
  postDate: "어제",
  isbn: "9788956609959",
  bookTitle: "이기적 유전자. 대충 되게 긴 제목입니다.",
  bookAuthor: "리처드 도킨스, 리처드 도킨스, 리처드 도킨스",
  contentBody:
    "밑줄 친 문장 정리 중. '생존'이라는 단어를 다시 생각하게 만드는 챕터였다. 밑줄 친 문장 정리 중. '생존'이라는 단어를 다시 생각하게 만드는 챕터였다. \n밑줄 친 문장 정리 중. '생존'이라는 단어를 다시 생각하게 만드는 챕터였다. 밑줄 친 문장 정리 중. '생존'이라는 단어를 다시 생각하게 만드는 챕터였다. 밑줄 친 문장 정리 중. '생존'이라는 단어를 다시 생각하게 만드는 챕터였다. 밑줄 친 문장 정리 중. '생존'이라는 단어를 다시 생각하게 만드는 챕터였다. 밑줄 친 문장 정리 중. '생존'이라는 단어를 다시 생각하게 만드는 챕터였다. 밑줄 친 문장 정리 중. '생존'이라는 단어를 다시 생각하게 만드는 챕터였다.",
  contentUrls: [
    "https://placehold.co/200x100/png",
    "https://placehold.co/200x400/png",
    "https://placehold.co/200x50/png",
    "https://placehold.co/200x800/png",
    "https://placehold.co/200x200/png",
  ],
  likeCount: 201,
  commentCount: 33,
  isSaved: true,
  isLiked: true,
  isWriter: false,
  tagList: [
    "#태그1",
    "#태그2",
    "#태그3",
    "#기나긴 태그1",
    "#기나긴 태그2",
    "#기나긴 태그3",
  ],
  isPublic: true,
};

export const DUMMY_COMMENT_REPLY_LIST: CommentReplyListType[] = [
  {
    commentId: 8,
    parentCommentCreatorNickname: "user1",
    creatorId: 12,
    creatorProfileImageUrl: "https://placehold.co/30/png",
    creatorNickname: "user12",
    aliasName: "칭호칭호",
    aliasColor: colors.character.mint,
    postDate: "12시간 전",
    content: "답글입니다.",
    likeCount: 5,
    isLike: false,
    isWriter: true,
  },
  {
    commentId: 456,
    parentCommentCreatorNickname: "user12",
    creatorId: 123,
    creatorProfileImageUrl: "https://placehold.co/30/png",
    creatorNickname: "user123",
    aliasName: "칭호칭호",
    aliasColor: colors.character.lavender,
    postDate: "8시간 전",
    content:
      "답글입니다. ~~~~~ 긴 댓글? 댓글 내용을 입력하세요. 긴 댓글? 댓글 내용을 입력하세요. 긴 댓글? 댓글 내용을 입력하세요. 긴 댓글? 댓글 내용을 입력하세요. 긴 댓글? 댓글 내용을 입력하세요. 긴 댓글? 댓글 내용을 입력하세요. 긴 댓글? 댓글 내용을 입력하세요.",
    likeCount: 9,
    isLike: false,
    isWriter: false,
  },
];

export const DUMMY_COMMENT_LIST: CommentListType[] = [
  {
    commentId: 3,
    creatorId: 5,
    creatorProfileImageUrl: "https://placehold.co/30/png",
    creatorNickname: "user1",
    aliasName: "칭호",
    aliasColor: colors.character.pink,
    postDate: "2026.02.12",
    content: `입력하세요. 댓글 내용을 입력하세요오.\n줄바꿈 할게요.\n댓글 내용을 입력하세요. 댓글 내용을 입력하세요. `,
    likeCount: 12,
    isLike: true,
    isDeleted: false,
    isWriter: false,
    replyList: DUMMY_COMMENT_REPLY_LIST,
  },
  {
    commentId: 123,
    creatorId: 16,
    creatorProfileImageUrl: "https://placehold.co/30/png",
    creatorNickname: "테스트유저16",
    aliasName: "칭호",
    aliasColor: colors.character.orange,
    postDate: "5시간 전",
    content: `입력하세요. 댓글 내용을 입력하세요오.\n줄바꿈 할게요.\n댓글 내용을 입력하세요. 댓글 내용을 입력하세요. `,
    likeCount: 135,
    isLike: true,
    isDeleted: false,
    isWriter: false,
    replyList: [],
  },
];
