import { colors } from "@theme/token";

export const DUMMY_MY_THIP_LIST = [
  {
    userId: 1,
    nickname: "user1234",
    profileImage: "https://placehold.co/36/png",
    aliasName: "칭호",
    aliasColor: colors.character.lavender,
    isFollowing: true,
  },
  {
    userId: 2,
    nickname: "test",
    profileImage: "https://placehold.co/36/png",
    aliasName: "칭호",
    aliasColor: colors.character.mint,
    isFollowing: true,
  },
  {
    userId: 3,
    nickname: "test123451234",
    profileImage: "https://placehold.co/36/png",
    aliasName: "칭호",
    aliasColor: colors.character.skyblue,
    isFollowing: true,
  },
  {
    userId: 4,
    nickname: "테스트 닉네임",
    profileImage: "https://placehold.co/36/png",
    aliasName: "칭호",
    aliasColor: colors.character.lavender,
    isFollowing: true,
  },
  {
    userId: 5,
    nickname: "thip123",
    profileImage: "https://placehold.co/36/png",
    aliasName: "칭호",
    aliasColor: colors.character.orange,
    isFollowing: true,
  },
  {
    userId: 6,
    nickname: "user2",
    profileImage: "https://placehold.co/36/png",
    aliasName: "칭호",
    aliasColor: colors.character.pink,
    isFollowing: true,
  },
  {
    userId: 7,
    nickname: "user356",
    profileImage: "https://placehold.co/36/png",
    aliasName: "칭호",
    aliasColor: colors.character.lavender,
    isFollowing: true,
  },
  {
    userId: 8,
    nickname: "테스트3",
    profileImage: "https://placehold.co/36/png",
    aliasName: "칭호",
    aliasColor: colors.character.mint,
    isFollowing: true,
  },
  {
    userId: 9,
    nickname: "thipthip",
    profileImage: "https://placehold.co/36/png",
    aliasName: "칭호",
    aliasColor: colors.character.skyblue,
    isFollowing: true,
  },
];
